int layer0[44] = {
  KEY_QUOTE, KEY_COMMA, KEY_PERIOD, KEY_P, KEY_Y, KEY_0, KEY_F, KEY_G, KEY_C, KEY_R, KEY_L,
  KEY_A, KEY_O, KEY_E, KEY_U, KEY_I, KEY_0, KEY_D, KEY_H, KEY_T, KEY_N, KEY_S,
  KEY_SEMICOLON, KEY_Q, KEY_J, KEY_K, KEY_X, KEYBOARD_LEFT_ALT, KEY_B, KEY_M, KEY_W, KEY_V, KEY_Z,
  KEY_ESC, KEY_TAB, KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_SHIFT, KEY_BACKSPACE, KEYBOARD_LEFT_CTRL, KEY_SPACE, PRE_FUNCTION(1), KEY_SLASH, KEY_MINUS, KEY_ENTER };

int layer1[44] = {
  SHIFT(KEY_1), SHIFT(KEY_2), SHIFT(KEY_3), SHIFT(KEY_4), SHIFT(KEY_5), KEY_0, SHIFT(KEY_6), SHIFT(KEY_7), SHIFT(KEY_8), SHIFT(KEY_9), SHIFT(KEY_0),
  KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_0, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0,
  SHIFT(KEY_TILDE), 0, 0, KEY_LEFT_BRACE, SHIFT(KEY_LEFT_BRACE), KEYBOARD_LEFT_ALT, SHIFT(KEY_RIGHT_BRACE), KEY_RIGHT_BRACE, KEY_BACKSLASH, KEY_BACKSPACE, KEY_EQUAL,
  FUNCTION(2), SHIFT(KEY_INSERT), KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_SHIFT, KEY_DELETE, KEYBOARD_LEFT_CTRL, KEY_SPACE, PRE_FUNCTION(1), 0, 0, 0 };

int layer2[44] = {
  KEY_HOME, KEY_UP, KEY_END, KEY_INSERT, KEY_PAGE_UP, KEY_0, KEY_UP, KEY_F7, KEY_F8, KEY_F9, KEY_F10,
  KEY_LEFT, KEY_DOWN, KEY_RIGHT, KEY_DELETE, KEY_PAGE_DOWN, KEY_0, KEY_DOWN, KEY_F4, KEY_F5, KEY_F6, KEY_F11,
  0, 0, 0, 0, 0, KEYBOARD_LEFT_ALT, 0, KEY_F1, KEY_F2, KEY_F3, KEY_F12,
  0, 0, KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_SHIFT, KEY_BACKSPACE, KEYBOARD_LEFT_CTRL, KEY_SPACE, PRE_FUNCTION(1), 0, 0, FUNCTION(0) };

int *layers[] = {layer0, layer1, layer2};

#include "layout_common.h"
